In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [22]:
X_train=pd.read_csv('Training Data/Diabetes_XTrain.csv')
Y_train=pd.read_csv('Training Data/Diabetes_YTrain.csv')

In [35]:
X_test=pd.read_csv('Test Cases/Diabetes_Xtest.csv')

In [37]:
X_test.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            0      180             90             26       90  36.5   
1            2       93             64             32      160  38.0   
2            2      114             68             22        0  28.7   
3           13       76             60              0        0  32.8   
4            1       80             74             11       60  30.0   

   DiabetesPedigreeFunction  Age  
0                     0.314   35  
1                     0.674   23  
2                     0.092   25  
3                     0.180   41  
4                     0.527   22

In [23]:
X_train.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age'],
      dtype='object')

In [24]:
X_train=X_train.values
Y_train=Y_train.values.reshape((-1))

In [25]:
X_train.shape,Y_train.shape

((576, 8), (576,))

In [27]:
X_train

array([[  7.   , 168.   ,  88.   , ...,  38.2  ,   0.787,  40.   ],
       [  8.   , 110.   ,  76.   , ...,  27.8  ,   0.237,  58.   ],
       [  7.   , 147.   ,  76.   , ...,  39.4  ,   0.257,  43.   ],
       ...,
       [  2.   , 122.   ,  60.   , ...,  29.8  ,   0.717,  22.   ],
       [  4.   , 154.   ,  72.   , ...,  31.3  ,   0.338,  37.   ],
       [  1.   ,  88.   ,  78.   , ...,  32.   ,   0.365,  29.   ]])

In [29]:
X_test=X_test.values

In [30]:
X_test

array([[0.00e+00, 1.80e+02, 9.00e+01, ..., 3.65e+01, 3.14e-01, 3.50e+01],
       [2.00e+00, 9.30e+01, 6.40e+01, ..., 3.80e+01, 6.74e-01, 2.30e+01],
       [2.00e+00, 1.14e+02, 6.80e+01, ..., 2.87e+01, 9.20e-02, 2.50e+01],
       ...,
       [0.00e+00, 1.62e+02, 7.60e+01, ..., 4.96e+01, 3.64e-01, 2.60e+01],
       [1.20e+01, 8.40e+01, 7.20e+01, ..., 2.97e+01, 2.97e-01, 4.60e+01],
       [0.00e+00, 9.40e+01, 0.00e+00, ..., 0.00e+00, 2.56e-01, 2.50e+01]])

### knn

In [15]:
def distance(x1,x2):
    return np.sqrt(sum((x1-x2)**2))

def knn(x,y,query_point,k=5):
    vals=[]
    m=x.shape[0]  # totak number of points
    for i in range(m):
        d=distance(query_point,x[i])
        vals.append((d,y[i])) # append distancce and label of point
        # d in first place because we have to sort list according to distance
    vals=sorted(vals)
    
    vals=vals[:k]    # k nearrest points
    vals=np.array(vals) 
    
    newlist=np.unique(vals[:,1],return_counts=True) 
    print(newlist)
    index=newlist[1].argmax()
    prediction=newlist[0][index]
    return prediction

In [34]:
knn(X_train,Y_train,X_test[3])
# ans is 0 means person dont have diabetes

(array([0.]), array([5]))


0.0